fix: use `chromium` browser instead of chrome
Get this issue with chrome inside docker found this solution proposed (not tested)
https://stackoverflow.com/questions/69081326/could-not-get-version-for-chrome-with-this-command-google-chrome-version-g
  self.browser_version = chrome_version(chrome_type)
  File "/usr/local/lib/python3.8/site-packages/webdriver_manager/utils.py", line 142, in chrome_version
    raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
ValueError: Could not get version for Chrome with this command: google-chrome --version || google-chrome-stable --version